name: Travis Neilson
markdown: redcarpet

# Excludes and Includes
exclude: [
  "node_modules",
  "gulpfile.js",
  "package.json",
  "preview.jpg",
  "README.md",
  "assets/css"
]
keep_files: ["assets/css/main.css"]